"""evidence core schema

Revision ID: 9432eff2dba5
Revises: 
Create Date: 2026-09-21 23:47:28.387251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9432eff2dba5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('overlap', sa.Integer(), nullable=False),
    sa.Column('splitter', sa.String(), nullable=False),
    sa.Column('parser_name', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorized_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('scope_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_sources_workspace_id'), 'authorized_sources', ['workspace_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('authorized_source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MISSING', 'REVOKED', 'TOMBSTONED', 'HARD_DELETE_PENDING', 'DELETED', name='source_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_source_id'], ['authorized_sources.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_authorized_source_id'), 'sources', ['authorized_source_id'], unique=False)
    op.create_index(op.f('ix_sources_workspace_id'), 'sources', ['workspace_id'], unique=False)
    op.create_table('evidence_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('parser_name', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_versions_content_hash'), 'evidence_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_versions_source_id'), 'evidence_versions', ['source_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PARTIAL', name='ingestion_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_source_id'), 'ingestion_jobs', ['source_id'], unique=False)
    op.create_table('evidence_units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evidence_version_id', sa.String(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_version_id'], ['evidence_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_units_evidence_version_id'), 'evidence_units', ['evidence_version_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('evidence_version_id', sa.String(), nullable=False),
    sa.Column('evidence_unit_id', sa.String(), nullable=False),
    sa.Column('chunk_recipe_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_recipe_id'], ['chunk_recipes.id'], ),
    sa.ForeignKeyConstraint(['evidence_unit_id'], ['evidence_units.id'], ),
    sa.ForeignKeyConstraint(['evidence_version_id'], ['evidence_versions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_chunk_recipe_id'), 'chunks', ['chunk_recipe_id'], unique=False)
    op.create_index(op.f('ix_chunks_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunks_evidence_unit_id'), 'chunks', ['evidence_unit_id'], unique=False)
    op.create_index(op.f('ix_chunks_evidence_version_id'), 'chunks', ['evidence_version_id'], unique=False)
    op.create_index(op.f('ix_chunks_source_id'), 'chunks', ['source_id'], unique=False)
    op.create_index('ix_chunks_source_id_content_hash', 'chunks', ['source_id', 'content_hash'], unique=False)
    # ### end Alembic commands ###

    # Standalone FTS5 virtual table for full-text search over chunk text.
    # Not a SQLAlchemy model: FTS5 virtual tables don't map cleanly onto the
    # ORM, so it's created/dropped here via raw SQL and kept in sync with
    # `chunks` by application code (or triggers added in a later checkpoint).
    op.execute("CREATE VIRTUAL TABLE fts_chunks USING fts5(chunk_id UNINDEXED, text)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE fts_chunks")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_source_id_content_hash', table_name='chunks')
    op.drop_index(op.f('ix_chunks_source_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_evidence_version_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_evidence_unit_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_content_hash'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_recipe_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_evidence_units_evidence_version_id'), table_name='evidence_units')
    op.drop_table('evidence_units')
    op.drop_index(op.f('ix_ingestion_jobs_source_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_evidence_versions_source_id'), table_name='evidence_versions')
    op.drop_index(op.f('ix_evidence_versions_content_hash'), table_name='evidence_versions')
    op.drop_table('evidence_versions')
    op.drop_index(op.f('ix_sources_workspace_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_authorized_source_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_authorized_sources_workspace_id'), table_name='authorized_sources')
    op.drop_table('authorized_sources')
    op.drop_table('workspaces')
    op.drop_table('chunk_recipes')
    # ### end Alembic commands ###
